### ISSUE TITLE
Export Proforma to Dispatch dont work

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#120]
link: http://roloffice.docksal/pidb/index.php?edit&pidb_id=4851&exportProformaToDispatch

Fatal error
: Uncaught BadMethodCallException: Undefined method "getProperties". The method name must start with either findBy, findOneBy or countBy! in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:252 Stack trace: #0 /var/www/templates/pidb/includes/export__proforma__to__dispatch.php(86): Doctrine\ORM\EntityRepository->__call('getProperties', Array) #1 /var/www/templates/pidb/includes/tools_menu.php(11): require('/var/www/templa...') #2 /var/www/templates/pidb/index.php(38): include('/var/www/templa...') #3 /var/www/web/pidb/index.php(12): include('/var/www/templa...') #4 {main} thrown in
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php
on line
252

**Comment by draganjancikin** [comment]
Resolved
