### ISSUE TITLE
Client view page bug

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#146]
When create a new client only with name, on client view page det bug:

Fatal error: Uncaught Doctrine\ORM\Exception\MissingIdentifierField: The identifier id is missing for a query of Roloffice\Entity\Country in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Exception/MissingIdentifierField.php:13 Stack trace: #0 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(449): Doctrine\ORM\Exception\MissingIdentifierField::fromFieldAndClass('id', 'Roloffice\\Entit...') #1 /var/www/templates/client/includes/tools_menu.php(33): Doctrine\ORM\EntityManager->find('\\Roloffice\\Enti...', Array) #2 /var/www/templates/client/index.php(38): include('/var/www/templa...') #3 /var/www/web/clients/index.php(10): include('/var/www/templa...') #4 {main} thrown in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Exception/MissingIdentifierField.php on line 13

**Comment by draganjancikin** [comment]
Resolved
