### ISSUE TITLE
Create an article issue

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#160]
Fatal error
: Uncaught Doctrine\DBAL\Driver\Mysqli\Exception\StatementError: Incorrect decimal value: '' for column `default`.`v6__articles`.`price` at row 1 in /var/www/vendor/doctrine/dbal/src/Driver/Mysqli/Exception/StatementError.php:21 Stack trace: #0 /var/www/vendor/doctrine/dbal/src/Driver/Mysqli/Statement.php(156): Doctrine\DBAL\Driver\Mysqli\Exception\StatementError::new(Object(mysqli_stmt)) #1 /var/www/vendor/doctrine/dbal/src/Statement.php(190): Doctrine\DBAL\Driver\Mysqli\Statement->execute(NULL) #2 /var/www/vendor/doctrine/dbal/src/Statement.php(249): Doctrine\DBAL\Statement->execute(NULL) #3 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(278): Doctrine\DBAL\Statement->executeStatement() #4 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1130): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() #5 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(427): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMe in
/var/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php
on line
117

**Comment by draganjancikin** [comment]
Resolved
