### ISSUE TITLE
Create a new "Narudzbenica"

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#163]
Notice
: Undefined offset: 1 in
/var/www/src/Repository/OrderRepository.php
on line
162

Fatal error
: Uncaught Error: Call to a member function getOrdinalNumInYear() on null in /var/www/src/Repository/OrderRepository.php:92 Stack trace: #0 /var/www/templates/order/includes/create.php(39): Roloffice\Repository\OrderRepository->setOrdinalNumInYear(1) #1 /var/www/templates/order/includes/tools__menu.php(2): require('/var/www/templa...') #2 /var/www/templates/order/index.php(38): include('/var/www/templa...') #3 /var/www/web/orders/index.php(10): include('/var/www/templa...') #4 {main} thrown in

**Comment by draganjancikin** [comment]
Resolved
