### ISSUE TITLE
Error on page: edit Material Supplier

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#164]
Fatal error
: Uncaught Doctrine\DBAL\Driver\Mysqli\Exception\StatementError: Data truncated for column 'price' at row 1 in /var/www/vendor/doctrine/dbal/src/Driver/Mysqli/Exception/StatementError.php:21 Stack trace: #0 /var/www/vendor/doctrine/dbal/src/Driver/Mysqli/Statement.php(156): Doctrine\DBAL\Driver\Mysqli\Exception\StatementError::new(Object(mysqli_stmt)) #1 /var/www/vendor/doctrine/dbal/src/Connection.php(1167): Doctrine\DBAL\Driver\Mysqli\Statement->execute() #2 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(523): Doctrine\DBAL\Connection->executeStatement('UPDATE v6__mate...', Array, Array) #3 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(409): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(Object(Roloffice\Entity\MaterialSupplier), 'v6__materials__...', Array, false) #4 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1219): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->update(Object(Roloffi in
/var/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php
on line
117

**Comment by draganjancikin** [comment]
Resolved
