### ISSUE TITLE
Error on page create a new Project

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#169]
Notice
: Undefined offset: 1 in
/var/www/src/Repository/ProjectRepository.php
on line
131

Fatal error
: Uncaught Error: Call to a member function getId() on null in /var/www/src/Repository/ProjectRepository.php:58 Stack trace: #0 /var/www/templates/project/includes/create_project.php(47): Roloffice\Repository\ProjectRepository->setOrdinalNumInYear(1) #1 /var/www/templates/project/includes/tools_menu.php(3): require('/var/www/templa...') #2 /var/www/templates/project/index.php(38): include('/var/www/templa...') #3 /var/www/web/projects/index.php(10): include('/var/www/templa...') #4 {main} thrown in
/var/www/src/Repository/ProjectRepository.php
on line
58

**Comment by draganjancikin** [comment]
resolved
