### ISSUE TITLE
Error on page create a new Cutting

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#173]
Notice
: Undefined offset: 1 in
/var/www/src/Repository/CuttingSheetRepository.php
on line
147

Fatal error
: Uncaught Error: Call to a member function getOrdinalNumInYear() on null in /var/www/src/Repository/CuttingSheetRepository.php:77 Stack trace: #0 /var/www/templates/cutting/includes/create.php(30): Roloffice\Repository\CuttingSheetRepository->setOrdinalNumInYear(1) #1 /var/www/templates/cutting/includes/tools__menu.php(2): require('/var/www/templa...') #2 /var/www/templates/cutting/index.php(38): include('/var/www/templa...') #3 /var/www/web/cutting/index.php(10): include('/var/www/templa...') #4 {main} thrown in
/var/www/src/Repository/CuttingSheetRepository.php
on line
77

**Comment by draganjancikin** [comment]
Resolved
