### ISSUE TITLE
Save new project on project page

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#49]
Warning: include (D:/RolostilFENCE/projekti/roloffice_dev/web/../src/Controller/Connection.php): failed to open stream: No such file or directory inD:\RolostilFENCE\projekti\roloffice_dev\web\autoload.php on line 4

Warning: include(): Failed opening 'D:/RolostilFENCE/projekti/roloffice_dev/web/../src/Controller/Connection.php' for inclusion (include_path='C:\xampp\php\PEAR') in D:\RolostilFENCE\projekti\roloffice_dev\web\autoload.php on line 4

Fatal error: Uncaught Error: Class 'Connection' not found in D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\add.php:15 Stack trace: #0 D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\toolsMenu.php(2): require() #1 D:\RolostilFENCE\projekti\roloffice_dev\templates\project\index.php(38): include('D:\\RolostilFENC...') #2 D:\RolostilFENCE\projekti\roloffice_dev\web\projects\index.php(14): include('D:\\RolostilFENC...') #3 {main} thrown in
D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\add.php on line 15

**Comment by draganjancikin** [comment]
Resolved
