### ISSUE TITLE
Fatal error : Uncaught Error: Class 'oloffice\Controller\DatabaseController'

### ISSUE THREAD

**Issue by draganjancikin** [draganjancikin/d-office#56]
Fatal error: Uncaught Error: Class 'oloffice\Controller\DatabaseController' not found in D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\edit.php:16 Stack trace: #0 D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\toolsMenu.php(3): require() #1 D:\RolostilFENCE\projekti\roloffice_dev\templates\project\index.php(38): include('D:\\RolostilFENC...') #2 D:\RolostilFENCE\projekti\roloffice_dev\web\projects\index.php(15): include('D:\\RolostilFENC...') #3 {main} thrown in
D:\RolostilFENCE\projekti\roloffice_dev\templates\project\includes\edit.php on line 16

**Comment by draganjancikin** [comment]
Resolved
